version: '3.0'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: nodejs
    restart: unless-stopped
    env_file: .dockerenv
    environment:
      - DATABASE_CONNECTION_STRING=mongodb://$DATABASE_USERNAME:$DATABASE_PASSWORD@$mongodb/?retryWrites=true&w=majority
    depends_on:
      - mongodb
      - redis
    ports:
      - "9999:9999"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network

  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_PASSWORD
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
  
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - redisdata:/data/redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
  redisdata:
